"""Submersion end-to-end encryption (rework.md E11): keyslots and the SBE1
envelope, verified byte-for-byte against Submersion's own known-answer
vectors (``tests/data/submersion/crypto/crypto_vectors.json``, generated by
the project's own ``scripts/generate_crypto_test_vectors.py`` from the same
primitives - argon2-cffi's Argon2id, cryptography's AES-256-GCM and HKDF -
ported here)."""
import base64
import json
import os

import pytest

from src.core.services.submersion import crypto as c

FIXTURE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "submersion", "crypto", "crypto_vectors.json")


def _b64(d, key):
    return base64.b64decode(d[key])


@pytest.fixture(scope="module")
def vectors():
    with open(FIXTURE) as f:
        return json.load(f)


# ---------------------------------------------------------------- primitives

def test_argon2id_matches_dart_vector(vectors):
    v = vectors["argon2id"]
    kdf = c.KdfParams(m=v["m"], t=v["t"], p=v["p"])
    kek = c.derive_kek(v["password"], _b64(v, "salt"), kdf)
    assert kek == _b64(v, "output")


def test_hkdf_data_key_matches_dart_vector(vectors):
    v = vectors["hkdfData"]
    assert v["info"] == "sbe:v1:data"
    assert c.derive_data_key(_b64(v, "ikm")) == _b64(v, "output")


def test_aes_gcm_matches_dart_vector_shape(vectors):
    """Not a Keyslots/SyncEnvelope call directly (those add their own framing);
    proves the raw primitive dive_sync relies on (cryptography's AESGCM,
    ciphertext||tag concatenation, AAD) matches what Submersion's own
    generator produced."""
    v = vectors["aesGcm"]
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    ct = AESGCM(_b64(v, "key")).encrypt(_b64(v, "nonce"), _b64(v, "plaintext"), v["aad"].encode())
    assert ct == _b64(v, "ciphertextWithTag")


# ---------------------------------------------------------------- envelope KATs

def test_open_envelope_plain_kat(vectors):
    v = vectors["envelopePlain"]
    out = c.open_envelope(_b64(v, "envelope"), _b64(v, "key"), v["keyId"], v["filename"])
    assert out == _b64(v, "plaintext")


def test_open_envelope_gzip_kat(vectors):
    v = vectors["envelopeGzip"]
    out = c.open_envelope(_b64(v, "envelope"), _b64(v, "key"), v["keyId"], v["filename"])
    assert out == _b64(v, "plaintext")


def test_seal_reproduces_dart_generated_envelope_bytes(vectors):
    """seal() with the vector's own nonce must reproduce its envelope
    byte-for-byte, not just round-trip through open()."""
    v = vectors["envelopePlain"]
    nonce = _b64(vectors["aesGcm"], "nonce")  # the fixed nonce every KAT in this file shares
    out = c.seal(_b64(v, "plaintext"), _b64(v, "key"), v["keyId"], v["filename"],
                 compress=False, nonce=nonce)
    assert out == _b64(v, "envelope")


def test_seal_open_round_trip_with_and_without_compression():
    key, key_id, name = os.urandom(32), "8f14e45f-ceea-467f-ab37-a10a8d5f4c11", "ssv1.x.cs.000000000001.json"
    plain = (b'{"a":1}' * 500)  # compresses well
    sealed = c.seal(plain, key, key_id, name)
    assert sealed[20] & 0x01 == 0x01  # gzip flag set
    assert len(sealed) < len(plain)
    assert c.open_envelope(sealed, key, key_id, name) == plain

    incompressible = os.urandom(64)
    sealed2 = c.seal(incompressible, key, key_id, name)
    assert sealed2[20] & 0x01 == 0x00  # random bytes don't compress smaller
    assert c.open_envelope(sealed2, key, key_id, name) == incompressible


def test_wrong_filename_aad_fails_authentication():
    key, key_id = os.urandom(32), "8f14e45f-ceea-467f-ab37-a10a8d5f4c11"
    sealed = c.seal(b"secret", key, key_id, "ssv1.x.manifest.json")
    with pytest.raises(c.EnvelopeCorruptError):
        c.open_envelope(sealed, key, key_id, "ssv1.y.manifest.json")


def test_bit_flip_fails_authentication():
    key, key_id, name = os.urandom(32), "8f14e45f-ceea-467f-ab37-a10a8d5f4c11", "ssv1.x.manifest.json"
    sealed = bytearray(c.seal(b"secret data", key, key_id, name, compress=False))
    sealed[-1] ^= 0x01
    with pytest.raises(c.EnvelopeCorruptError):
        c.open_envelope(bytes(sealed), key, key_id, name)


def test_wrong_library_key_raises_with_the_actual_key_id():
    key, name = os.urandom(32), "ssv1.x.manifest.json"
    real_id = "8f14e45f-ceea-467f-ab37-a10a8d5f4c11"
    sealed = c.seal(b"data", key, real_id, name)
    with pytest.raises(c.WrongLibraryKeyError) as ei:
        c.open_envelope(sealed, key, "00000000-0000-0000-0000-000000000000", name)
    assert ei.value.library_key_id == real_id


def test_has_magic_and_library_key_id_of():
    key_id = "8f14e45f-ceea-467f-ab37-a10a8d5f4c11"
    env = c.seal(b"x", os.urandom(32), key_id, "n")
    assert c.has_magic(env) and not c.has_magic(b'{"json":1}')
    assert c.library_key_id_of(env) == key_id
    with pytest.raises(c.EnvelopeCorruptError):
        c.library_key_id_of(b"\x01\x02\x03")


def test_open_rejects_a_truncated_or_garbage_blob():
    with pytest.raises(c.EnvelopeCorruptError):
        c.open_envelope(b"not an envelope", os.urandom(32), "8f14e45f-ceea-467f-ab37-a10a8d5f4c11", "n")


def test_open_refuses_a_gzip_bomb_inside_an_authentic_envelope():
    key, key_id, name = os.urandom(32), "8f14e45f-ceea-467f-ab37-a10a8d5f4c11", "n"
    huge = b"\x00" * (10 * 1024 * 1024)  # 10 MiB of zeros compresses tiny
    sealed = c.seal(huge, key, key_id, name)
    with pytest.raises(c.EnvelopeCorruptError, match="inflated past"):
        c.open_envelope(sealed, key, key_id, name, max_plaintext_bytes=1024 * 1024)
    # under the cap it opens fine
    assert c.open_envelope(sealed, key, key_id, name) == huge


# ---------------------------------------------------------------- keyslots

def test_create_slot_then_unwrap_returns_the_mlk():
    mlk = bytes((i * 7) % 256 for i in range(32))
    kdf = c.KdfParams(m=1024, t=3, p=1)  # small params keep the test fast
    slot = c.create_slot("passphrase", "open sesame 42", mlk, kdf=kdf)
    file = c.KeyslotFile(version=1, library_key_id="8f14e45f-ceea-467f-ab37-a10a8d5f4c11", slots=[slot])
    assert c.try_unwrap(file, "open sesame 42") == mlk


def test_wrong_secret_returns_none():
    mlk = bytes(range(32))
    kdf = c.KdfParams(m=1024, t=3, p=1)
    slot = c.create_slot("passphrase", "right", mlk, kdf=kdf)
    file = c.KeyslotFile(version=1, library_key_id="8f14e45f-ceea-467f-ab37-a10a8d5f4c11", slots=[slot])
    assert c.try_unwrap(file, "wrong") is None


def test_recovery_slot_normalizes_before_unwrap():
    mlk = bytes(range(32))
    kdf = c.KdfParams(m=1024, t=3, p=1)
    code = "acid-acorn-acre-act-add-age-aid-aim"
    slot = c.create_slot("recovery", code, mlk, kdf=kdf)
    file = c.KeyslotFile(version=1, library_key_id="8f14e45f-ceea-467f-ab37-a10a8d5f4c11", slots=[slot])
    # entered with different case/whitespace, still unwraps
    assert c.try_unwrap(file, "  ACID  ACORN-acre act--add age aid aim ") == mlk


def test_keyslot_file_json_round_trips_and_matches_spec_shape():
    mlk = bytes((32 - i) % 256 for i in range(32))
    kdf = c.KdfParams(m=1024, t=3, p=1)
    p = c.create_slot("passphrase", "p", mlk, kdf=kdf)
    r = c.create_slot("recovery", "acid-acorn-acre-act-add-age-aid-aim", mlk, kdf=kdf)
    file = c.KeyslotFile(version=1, library_key_id="8f14e45f-ceea-467f-ab37-a10a8d5f4c11", slots=[p, r])
    raw = file.to_json_bytes()
    decoded = json.loads(raw)
    assert decoded["version"] == 1 and decoded["libraryKeyId"] == file.library_key_id
    assert len(decoded["slots"]) == 2 and decoded["slots"][0]["kdf"]["alg"] == "argon2id"
    back = c.KeyslotFile.from_json_bytes(raw)
    assert c.try_unwrap(back, "p") == mlk


def test_with_replaced_slot_swaps_by_type():
    mlk = bytes(range(32))
    kdf = c.KdfParams(m=1024, t=3, p=1)
    p1 = c.create_slot("passphrase", "one", mlk, kdf=kdf)
    p2 = c.create_slot("passphrase", "two", mlk, kdf=kdf)
    file = c.KeyslotFile(version=1, library_key_id="k", slots=[p1]).with_replaced_slot(p2)
    assert len(file.slots) == 1
    assert c.try_unwrap(file, "one") is None
    assert c.try_unwrap(file, "two") == mlk


def test_multiple_slots_first_wrong_second_right():
    mlk = bytes(range(32))
    kdf = c.KdfParams(m=1024, t=3, p=1)
    p = c.create_slot("passphrase", "pw", mlk, kdf=kdf)
    r = c.create_slot("recovery", "acid-acorn-acre-act-add-age-aid-aim", mlk, kdf=kdf)
    file = c.KeyslotFile(version=1, library_key_id="k", slots=[p, r])
    assert c.try_unwrap(file, "acid-acorn-acre-act-add-age-aid-aim") == mlk
