"""Submersion end-to-end encryption: keyslots and the SBE1 file envelope
(rework.md Track E, step E11).

A Python port of Submersion's ``lib/core/services/sync/crypto/keyslots.dart``
and ``sync_envelope.dart`` (github.com/submersion-app/submersion, commit
``2debe84``, 2026-09-20). Re-verify against the source if Submersion changes
its crypto format.

dive_sync only ever *joins* an already-encrypted library as a peer device; it
never enables encryption, rotates keys or issues recovery codes (all
Submersion-app-only lifecycle actions). What it needs is exactly: given the
cloud's ``submersion_keyslots.json`` and the user's passphrase, recover the
master library key (MLK), derive the data key that actually encrypts every
``ssv1.*`` file, and seal/open the SBE1 envelope around them.

Format, byte for byte:
  Keyslot wrapping: Argon2id(passphrase, salt, m/t/p) -> KEK;
    AES-256-GCM(MLK) under KEK -> {salt, kdf params, nonce, ciphertext||tag}.
  Data key: HKDF-SHA256(IKM=MLK, salt=b"", info=b"sbe:v1:data") -> 32 bytes.
  SBE1 envelope: "SBE1"(4) | libraryKeyId(16, raw UUID bytes) | flags(1,
    bit0=gzip) | nonce(12) | AES-256-GCM ciphertext || tag(16). AAD is the
    UTF-8 logical filename (so an envelope moved/renamed fails to open).

``createSlot``/``deriveKek``/``tryUnwrap`` and the envelope's ``seal``/
``open`` are verified byte-for-byte against Submersion's own committed known-
answer vectors (``tests/data/submersion/crypto/crypto_vectors.json``, itself
generated by the project's ``scripts/generate_crypto_test_vectors.py`` using
the same Python primitives ported here: ``argon2-cffi`` and ``cryptography``).
"""
from __future__ import annotations

import base64
import gzip
import os
import uuid
import zlib
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from argon2.low_level import Type, hash_secret_raw
from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

DATA_KEY_INFO = b"sbe:v1:data"


class CryptoError(RuntimeError):
    pass


class EnvelopeCorruptError(CryptoError):
    """An SBE1 envelope failed structural parsing or authentication -
    corrupt, tampered, or opened under the wrong filename/data key."""


class WrongLibraryKeyError(CryptoError):
    """The envelope is a well-formed SBE1 file, but stamped with a
    different libraryKeyId than the one dive_sync unlocked."""

    def __init__(self, library_key_id: str, message: str = "File is encrypted under a different library key"):
        super().__init__(message)
        self.library_key_id = library_key_id


# ---------------------------------------------------------------------------
# Keyslots: passphrase -> KEK -> unwrap the master library key (MLK)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class KdfParams:
    """Argon2id parameters. ``m`` is in 1-KiB blocks (65536 = 64 MiB), matching
    Submersion's own default; a keyslot carries its own params so they can be
    raised later without touching slots already at a lower cost."""
    alg: str = "argon2id"
    m: int = 65536
    t: int = 3
    p: int = 1

    def to_json(self) -> Dict[str, Any]:
        return {"alg": self.alg, "m": self.m, "t": self.t, "p": self.p}

    @classmethod
    def from_json(cls, data: Dict[str, Any]) -> "KdfParams":
        return cls(alg=data["alg"], m=data["m"], t=data["t"], p=data["p"])


@dataclass(frozen=True)
class Keyslot:
    """One wrapped copy of the master library key."""
    type: str  # 'passphrase' | 'recovery'
    salt: bytes
    kdf: KdfParams
    nonce: bytes
    wrapped: bytes  # AES-256-GCM(MLK) ciphertext || 16-byte tag

    def to_json(self) -> Dict[str, Any]:
        return {
            "type": self.type,
            "salt": base64.b64encode(self.salt).decode("ascii"),
            "kdf": self.kdf.to_json(),
            "nonce": base64.b64encode(self.nonce).decode("ascii"),
            "wrapped": base64.b64encode(self.wrapped).decode("ascii"),
        }

    @classmethod
    def from_json(cls, data: Dict[str, Any]) -> "Keyslot":
        return cls(
            type=data["type"],
            salt=base64.b64decode(data["salt"]),
            kdf=KdfParams.from_json(data["kdf"]),
            nonce=base64.b64decode(data["nonce"]),
            wrapped=base64.b64decode(data["wrapped"]),
        )


@dataclass(frozen=True)
class KeyslotFile:
    """The one plaintext cloud file holding every wrapped copy of the master
    library key. Never itself SBE1-encrypted (it is what makes decrypting
    everything else possible)."""

    CLOUD_FILE_NAME = "submersion_keyslots.json"

    version: int
    library_key_id: str
    slots: List[Keyslot] = field(default_factory=list)

    def to_json_bytes(self) -> bytes:
        import json
        return json.dumps({
            "version": self.version,
            "libraryKeyId": self.library_key_id,
            "slots": [s.to_json() for s in self.slots],
        }).encode("utf-8")

    @classmethod
    def from_json_bytes(cls, data: bytes) -> "KeyslotFile":
        import json
        obj = json.loads(data.decode("utf-8"))
        return cls(
            version=obj["version"],
            library_key_id=obj["libraryKeyId"],
            slots=[Keyslot.from_json(s) for s in obj["slots"]],
        )

    def with_replaced_slot(self, slot: Keyslot) -> "KeyslotFile":
        """Replace the slot sharing ``slot``'s type, or append when absent."""
        return KeyslotFile(
            version=self.version,
            library_key_id=self.library_key_id,
            slots=[s for s in self.slots if s.type != slot.type] + [slot],
        )


def normalize_recovery_code(text: str) -> str:
    """Lowercase; any run of whitespace/hyphens becomes a single hyphen -
    matches ``RecoveryCode.normalize`` so a recovery-code slot unwraps
    regardless of how the user typed it back in."""
    import re
    return re.sub(r"[\s\-]+", "-", text.strip().lower())


def derive_kek(secret: str, salt: bytes, kdf: KdfParams) -> bytes:
    """Argon2id key-encryption-key for one keyslot."""
    return hash_secret_raw(
        secret=secret.encode("utf-8"), salt=salt,
        time_cost=kdf.t, memory_cost=kdf.m, parallelism=kdf.p,
        hash_len=32, type=Type.ID,
    )


def create_slot(type_: str, secret: str, mlk: bytes, kdf: KdfParams = KdfParams(),
                salt: Optional[bytes] = None, nonce: Optional[bytes] = None) -> Keyslot:
    """Wrap ``mlk`` under a KEK derived from ``secret``. dive_sync itself
    never creates a library's first keyslot (that is Submersion's own
    "enable encryption" flow) - this exists for changePassphrase-equivalent
    tooling and for tests to build known-good fixtures without a live
    encrypted account."""
    salt = salt if salt is not None else os.urandom(16)
    nonce = nonce if nonce is not None else os.urandom(12)
    kek = derive_kek(secret, salt, kdf)
    wrapped = AESGCM(kek).encrypt(nonce, mlk, None)
    return Keyslot(type=type_, salt=salt, kdf=kdf, nonce=nonce, wrapped=wrapped)


def try_unwrap(file: KeyslotFile, secret: str) -> Optional[bytes]:
    """The master library key, or ``None`` when ``secret`` (a passphrase or a
    recovery code) matches none of the file's slots."""
    for slot in file.slots:
        candidate = normalize_recovery_code(secret) if slot.type == "recovery" else secret
        kek = derive_kek(candidate, slot.salt, slot.kdf)
        try:
            return AESGCM(kek).decrypt(slot.nonce, slot.wrapped, None)
        except InvalidTag:
            continue
    return None


def derive_sub_key(mlk: bytes, info: bytes) -> bytes:
    """A purpose-bound subkey from the master key, namespaced by ``info`` so
    the master key itself never touches data directly (HKDF-SHA256, RFC 5869
    default empty salt)."""
    return HKDF(algorithm=hashes.SHA256(), length=32, salt=None, info=info).derive(mlk)


def derive_data_key(mlk: bytes) -> bytes:
    return derive_sub_key(mlk, DATA_KEY_INFO)


# ---------------------------------------------------------------------------
# SBE1 envelope
# ---------------------------------------------------------------------------

MAGIC = b"SBE1"
_HEADER_LEN = 4 + 16 + 1 + 12
_FLAG_GZIP = 0x01
# A quarter gigabyte of plaintext is already past what any legitimate
# Submersion sync payload can be (the only structurally unbounded kind, a
# changeset, is built and JSON-encoded whole in memory on both ends first);
# past this, refuse to inflate rather than risk a decompression bomb.
DEFAULT_MAX_PLAINTEXT_BYTES = 256 * 1024 * 1024


def has_magic(data: bytes) -> bool:
    return data[:4] == MAGIC


def library_key_id_of(data: bytes) -> str:
    if not has_magic(data) or len(data) < _HEADER_LEN:
        raise EnvelopeCorruptError("Not an SBE1 envelope")
    return str(uuid.UUID(bytes=data[4:20]))


def seal(plaintext: bytes, data_key: bytes, library_key_id: str, filename: str,
         compress: bool = True, max_plaintext_bytes: int = DEFAULT_MAX_PLAINTEXT_BYTES,
         nonce: Optional[bytes] = None) -> bytes:
    payload = plaintext
    flags = 0
    if compress and len(plaintext) <= max_plaintext_bytes:
        gz = gzip.compress(plaintext, compresslevel=9, mtime=0)
        if len(gz) < len(plaintext):
            payload = gz
            flags |= _FLAG_GZIP
    nonce = nonce if nonce is not None else os.urandom(12)
    ciphertext = AESGCM(data_key).encrypt(nonce, payload, filename.encode("utf-8"))
    key_id_bytes = uuid.UUID(library_key_id).bytes
    return MAGIC + key_id_bytes + bytes([flags]) + nonce + ciphertext


def open_envelope(envelope: bytes, data_key: bytes, expected_library_key_id: str, filename: str,
                  max_plaintext_bytes: int = DEFAULT_MAX_PLAINTEXT_BYTES) -> bytes:
    if not has_magic(envelope) or len(envelope) < _HEADER_LEN + 16:
        raise EnvelopeCorruptError("Not an SBE1 envelope")
    key_id = library_key_id_of(envelope)
    if key_id != expected_library_key_id.lower():
        raise WrongLibraryKeyError(key_id)
    flags = envelope[20]
    nonce = envelope[21:33]
    body = envelope[_HEADER_LEN:]
    try:
        payload = AESGCM(data_key).decrypt(nonce, body, filename.encode("utf-8"))
    except InvalidTag as e:
        raise EnvelopeCorruptError("Envelope failed authentication (corrupt, tampered, or wrong name)") from e
    if flags & _FLAG_GZIP:
        # Bounded, chunked inflate: refuse a decompression bomb rather than
        # materialise it whole. AES-GCM already authenticated ``payload``
        # above, so this only guards against a within-trust-boundary peer
        # writing a hostile gzip stream, not a network attacker.
        decompressor = zlib.decompressobj(zlib.MAX_WBITS | 16)
        out = bytearray()
        try:
            for i in range(0, len(payload), 64 * 1024):
                out += decompressor.decompress(payload[i:i + 64 * 1024], max_plaintext_bytes - len(out) + 1)
                if len(out) > max_plaintext_bytes:
                    raise EnvelopeCorruptError(f"Envelope payload rejected: inflated past {max_plaintext_bytes} bytes")
            out += decompressor.flush()
        except zlib.error as e:
            raise EnvelopeCorruptError(f"Envelope payload rejected: {e}") from e
        if len(out) > max_plaintext_bytes:
            raise EnvelopeCorruptError(f"Envelope payload rejected: inflated past {max_plaintext_bytes} bytes")
        return bytes(out)
    return payload
